apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo-app
data:
  # Database configuration
  MONGODB_URI: "mongodb://mongodb-service:27017/todoapp"

  # Backend configuration
  PORT: "5000"
  NODE_ENV: "production"

  # Frontend configuration (not used in React build, but kept for consistency)
  REACT_APP_API_URL: "http://localhost:30001/api"
